apiVersion: apps/v1
kind: Deployment
metadata:
  name: otter-alert
  labels:
    app: otter-alert
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otter-alert
  template:
    metadata:
      labels:
        app: otter-alert
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: otter-alert
          image: xmapst/otter-alert:latest
          args:
            - --zookeeper=zknode-1:2181,zknode-2:2181,zknode-3:2181
            - --manager.database=username:password@tcp(mysqlhost:3306)/otter?charset=utf8&parseTime=True&loc=Local
            - --manager.endpoint=http://otter-manager:8080
            - --manager.username=admin
            - --manager.password=admin
            - --notification.type=dingtalk
            - --notification.url=https://oapi.dingtalk.com/robot/send?access_token=xxxxx-xxxxxxxx-xxxxxxxxxx
            - --notification.secret=SECxxxxxxxxxxxxxxxxxxxxx
