name: PublishToDockerhub

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            xmapst/otter-alert:latest
            xmapst/otter-alert:${{ env.GIT_TAG_NAME }}
